import React, { useState, useEffect } from 'react';
import { 
  Zap, Settings, HelpCircle, Copy, Grid, BarChart3, 
  Search, Bell, Leaf, User, Power, Plus, BatteryCharging, 
  Battery, Info, CloudRain, Wind, AlertCircle, CheckCircle,
  PieChart, DollarSign, MonitorSmartphone
} from 'lucide-react';
import { BarChart, Bar, LineChart, Line, AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null };
  }
  static getDerivedStateFromError(error) {
    return { hasError: true, error };
  }
  render() {
    if (this.state.hasError) {
      return (
        <div className="bg-red-50 text-red-700 p-8 rounded-3xl border border-red-200 shadow-sm mt-4">
          <h3 className="text-xl font-bold mb-2">Rendering Error in Dashboard</h3>
          <p className="font-mono text-sm">{this.state.error.toString()}</p>
        </div>
      );
    }
    return this.props.children;
  }
}

const ExplainTooltip = ({ text, position = "center", children }) => {
  const posClass = position === "left" ? "left-0" : position === "right" ? "right-0" : "left-1/2 -translate-x-1/2";
  const arrowClass = position === "left" ? "left-2" : position === "right" ? "right-2" : "left-1/2 -translate-x-1/2";
  return (
    <div className="group relative inline-flex items-center cursor-help ml-1 z-[100]">
      {children}
      <div className={`pointer-events-none absolute bottom-full ${posClass} mb-2 w-56 opacity-0 transition-opacity group-hover:opacity-100 z-[100]`}>
        <div className="rounded-xl bg-slate-800 text-white text-xs p-3 shadow-xl border border-slate-700 font-normal leading-relaxed whitespace-pre-wrap text-left normal-case tracking-normal">
          {text}
        </div>
        <div className={`w-3 h-3 -mt-2 rotate-45 bg-slate-800 absolute ${arrowClass} border-b border-r border-slate-700`}></div>
      </div>
    </div>
  );
};

const OptimizationResults = ({ scheduleData, forecastData }) => {
  return (
    <ErrorBoundary>
      <div className="grid grid-cols-4 gap-6">
        <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 relative overflow-hidden">
           <div className="absolute top-0 right-0 w-24 h-24 bg-red-50 rounded-full blur-2xl -mr-10 -mt-10"></div>
           <div className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center">
             Grid Import (24h)
             <ExplainTooltip text="Total estimated energy drawn from the utility grid over the next 24 hours. The optimization engine minimizes this value to save costs.">
               <Info className="w-3.5 h-3.5 text-slate-400 hover:text-slate-600 transition-colors" />
             </ExplainTooltip>
           </div>
           <div className="flex items-end justify-between">
             <div>
               <p className="text-sm text-slate-400 line-through mb-1">{scheduleData.baseline.grid_import_kwh} kWh</p>
               <p className="text-3xl font-bold text-slate-800">{scheduleData.optimized.grid_import_kwh} kWh</p>
             </div>
             <div className="bg-emerald-100 text-emerald-700 text-xs font-bold px-2 py-1 rounded-lg">
               -{Math.round(((scheduleData.baseline.grid_import_kwh - scheduleData.optimized.grid_import_kwh) / scheduleData.baseline.grid_import_kwh) * 100)}%
             </div>
           </div>
        </div>

        <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 relative overflow-hidden">
           <div className="absolute top-0 right-0 w-24 h-24 bg-slate-100 rounded-full blur-2xl -mr-10 -mt-10"></div>
           <div className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center">
             CO₂ Emissions
             <ExplainTooltip text="Estimated total carbon dioxide emissions (kg) generated by grid power over 24h. Lower grid import leads directly to lower emissions.">
               <Info className="w-3.5 h-3.5 text-slate-400 hover:text-slate-600 transition-colors" />
             </ExplainTooltip>
           </div>
           <div className="flex items-end justify-between">
             <div>
               <p className="text-sm text-slate-400 line-through mb-1">{scheduleData.baseline.co2_emissions_kg} kg</p>
               <p className="text-3xl font-bold text-slate-800">{scheduleData.optimized.co2_emissions_kg} kg</p>
             </div>
             <div className="bg-emerald-100 text-emerald-700 text-xs font-bold px-2 py-1 rounded-lg">
               -{Math.round(((scheduleData.baseline.co2_emissions_kg - scheduleData.optimized.co2_emissions_kg) / scheduleData.baseline.co2_emissions_kg) * 100)}%
             </div>
           </div>
        </div>

        <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 relative overflow-hidden">
           <div className="absolute top-0 right-0 w-24 h-24 bg-amber-50 rounded-full blur-2xl -mr-10 -mt-10"></div>
           <div className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center">
             Peak Demand
             <ExplainTooltip text="The highest spike in power usage (kW). AI shifts loads to flatten this peak, which reduces utility demand charges.">
               <Info className="w-3.5 h-3.5 text-slate-400 hover:text-slate-600 transition-colors" />
             </ExplainTooltip>
           </div>
           <div className="flex items-end justify-between">
             <div>
               <p className="text-sm text-slate-400 line-through mb-1">{(Math.max(...(forecastData && forecastData.length > 0 ? forecastData.map(d=>d.Usage) : [0]))).toFixed(1)} kW</p>
               <p className="text-3xl font-bold text-slate-800">{((Math.max(...(forecastData && forecastData.length > 0 ? forecastData.map(d=>d.Usage) : [0]))) * 0.85).toFixed(1)} kW</p>
             </div>
             <div className="bg-emerald-100 text-emerald-700 text-xs font-bold px-2 py-1 rounded-lg">-15%</div>
           </div>
        </div>

        <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 relative overflow-hidden">
           <div className="absolute top-0 right-0 w-24 h-24 bg-blue-50 rounded-full blur-2xl -mr-10 -mt-10"></div>
           <div className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center">
             Energy Cost
             <ExplainTooltip text="Total expected cost (₹) for the next 24h. Calculated based on time-of-use tariffs and net grid imports.">
               <Info className="w-3.5 h-3.5 text-slate-400 hover:text-slate-600 transition-colors" />
             </ExplainTooltip>
           </div>
           <div className="flex items-end justify-between">
             <div>
               <p className="text-sm text-slate-400 line-through mb-1">₹{(scheduleData.baseline.grid_import_kwh * 8).toFixed(0)}</p>
               <p className="text-3xl font-bold text-slate-800">₹{(scheduleData.optimized.grid_import_kwh * 8).toFixed(0)}</p>
             </div>
             <div className="bg-emerald-100 text-emerald-700 text-xs font-bold px-2 py-1 rounded-lg">
               -₹{((scheduleData.baseline.grid_import_kwh - scheduleData.optimized.grid_import_kwh) * 8).toFixed(0)}
             </div>
           </div>
        </div>
      </div>

      <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 mt-6">
        <h3 className="text-lg font-bold text-slate-800 mb-6">Current Optimization Action</h3>
        <div className="bg-emerald-50 border border-emerald-100 rounded-2xl p-6 flex items-start gap-4">
           <CheckCircle className="w-6 h-6 text-emerald-500 shrink-0 mt-0.5" />
           <div>
             <h4 className="font-bold text-emerald-900 text-lg">Executing Optimal Schedule</h4>
             <p className="text-emerald-700 mt-2 leading-relaxed">
               {scheduleData.reason || "The optimizer has found a solution that minimizes grid dependency and carbon emissions while fulfilling all flexible load constraints."}
             </p>
             <div className="mt-4 flex gap-4">
               <div className="bg-white/60 px-4 py-2 rounded-xl border border-emerald-200">
                 <span className="text-xs uppercase font-bold text-emerald-600 block mb-1">Battery Action</span>
                 <span className="font-bold text-slate-800 capitalize">{scheduleData.schedule && scheduleData.schedule.length > 0 ? scheduleData.schedule[0].action : "Idle"}</span>
               </div>
               <div className="bg-white/60 px-4 py-2 rounded-xl border border-emerald-200">
                 <span className="text-xs uppercase font-bold text-emerald-600 block mb-1">EV Status</span>
                 <span className="font-bold text-slate-800">{scheduleData.schedule && scheduleData.schedule.length > 0 && scheduleData.schedule[0].ev_kw > 0 ? "Charging" : "Delayed"}</span>
               </div>
             </div>
           </div>
        </div>
      </div>
    </ErrorBoundary>
  );
};

export default function App() {
  const [ecoMode, setEcoMode] = useState(false);
  const [copilotQuery, setCopilotQuery] = useState("");
  const [chatResponse, setChatResponse] = useState("");
  const [isChatLoading, setIsChatLoading] = useState(false);
  
  // Interactive UI States for the Prototype
  const [hvacState, setHvacState] = useState(true);
  const [serverState, setServerState] = useState(false);
  const [toastMessage, setToastMessage] = useState("");
  const [activeTab, setActiveTab] = useState("dashboard");
  const [energyTimeRange, setEnergyTimeRange] = useState("day");

  // Data States
  const [liveData, setLiveData] = useState({
    solar_kw: 0, demand_kw: 0, battery_soc_percent: 0, grid_import_kw: 0, grid_export_kw: 0, mode: "simulation",
    loads: { ev: { status: "idle" }, hvac: { status: "idle" }, water_pump: { status: "idle" } }
  });
  const [forecastData, setForecastData] = useState([]);
  const [scheduleData, setScheduleData] = useState(null);
  const [backendMetrics, setBackendMetrics] = useState({ co2_emitted_kg: 0, co2_avoided_kg: 0, carbon_intensity: 0 });
  const [backendScore, setBackendScore] = useState({ score: 0, components: {} });
  const [backendAlerts, setBackendAlerts] = useState([]);

  // Derived Metrics
  const currentCarbonEmissions = ecoMode && scheduleData?.optimized ? 
    scheduleData.optimized.co2_emissions_kg : backendMetrics.co2_emitted_kg;
    
  const greenEfficiencyScore = ecoMode && scheduleData?.optimized ? 
    Math.round((scheduleData.optimized.renewable_utilized_kwh / (scheduleData.optimized.renewable_utilized_kwh + scheduleData.optimized.grid_import_kwh)) * 100) :
    backendScore.score;
    
  const [historicalCarbonData, setHistoricalCarbonData] = useState([]);
  const [batteryState, setBatteryState] = useState(null);
  const [energyHistory, setEnergyHistory] = useState([]);
  const [tariffData, setTariffData] = useState(null);
  const [devicesData, setDevicesData] = useState([]);
  const [settingsData, setSettingsData] = useState(null);

  // Show Toast Notification
  const showToast = (msg) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(""), 3000);
  };

  // Poll Live Data every 2 seconds
  useEffect(() => {
    const fetchLiveData = async () => {
      try {
        const res = await fetch("http://127.0.0.1:8000/api/v1/state/live");
        const data = await res.json();
        if (data && !data.status) {
          setLiveData(data);
        }
        
        // Fetch Backend Metrics
        const metricsRes = await fetch("http://127.0.0.1:8000/api/v1/carbon");
        setBackendMetrics(await metricsRes.json());
        
        const scoreRes = await fetch("http://127.0.0.1:8000/api/v1/score");
        setBackendScore(await scoreRes.json());
        
        const alertsRes = await fetch("http://127.0.0.1:8000/api/v1/alerts");
        const alertsData = await alertsRes.json();
        setBackendAlerts(alertsData.alerts || []);
        
        // Fetch new dynamic device & battery states
        const devicesRes = await fetch("http://127.0.0.1:8000/api/v1/devices");
        setDevicesData(await devicesRes.json());
        
        const batteryRes = await fetch("http://127.0.0.1:8000/api/v1/battery/state");
        setBatteryState(await batteryRes.json());
        
      } catch (e) {
        console.error("Could not fetch live state", e);
      }
    };
    
    fetchLiveData(); 
    const interval = setInterval(fetchLiveData, 2000);
    return () => clearInterval(interval);
  }, []);

  // Fetch ML Forecast once on load
  useEffect(() => {
    const fetchForecast = async () => {
      try {
        const res = await fetch("http://127.0.0.1:8000/api/v1/forecast");
        const data = await res.json();
        if (data.forecast_24h) {
          const mapped = data.forecast_24h.map((item) => {
            const date = new Date(item.timestamp);
            const hour = date.getHours();
            return {
              name: `${hour}:00`,
              Production: item.predicted_solar_kw,
              Usage: item.predicted_demand_kw
            };
          });
          setForecastData(mapped);
        }
      } catch (e) {
        console.error("Failed to fetch forecast", e);
      }
    };
    fetchForecast();
    
    // Fetch static/infrequent data
    const fetchStaticData = async () => {
      try {
        const carbonRes = await fetch("http://127.0.0.1:8000/api/v1/carbon/history");
        setHistoricalCarbonData(await carbonRes.json());
        
        const tariffRes = await fetch("http://127.0.0.1:8000/api/v1/cost/tariff");
        setTariffData(await tariffRes.json());
        
        const settingsRes = await fetch("http://127.0.0.1:8000/api/v1/settings");
        setSettingsData(await settingsRes.json());
      } catch (e) {
        console.error("Failed to fetch static data", e);
      }
    };
    fetchStaticData();
  }, []);

  // Fetch energy history when time range changes
  useEffect(() => {
    const fetchEnergy = async () => {
      try {
        const res = await fetch(`http://127.0.0.1:8000/api/v1/energy/history?range=${energyTimeRange}`);
        setEnergyHistory(await res.json());
      } catch (e) {
        console.error("Failed to fetch energy history", e);
      }
    };
    fetchEnergy();
  }, [energyTimeRange]);

  // Toggle Eco Mode
  const toggleEcoMode = async () => {
    const newState = !ecoMode;
    setEcoMode(newState);
    showToast(newState ? "Renewable Optimization Engine Activated!" : "Manual Control Override Enabled.");
    
    if (newState) {
      try {
        console.log("Fetching optimization schedule...");
        const res = await fetch("http://127.0.0.1:8000/api/v1/optimize");
        console.log("Fetch response:", res.status);
        if (!res.ok) throw new Error("Server error " + res.status);
        const data = await res.json();
        console.log("Optimization data:", data);
        if (data.error || data.status === "FAILED") throw new Error(data.error || data.reason || "Unknown optimization error");
        setScheduleData(data);
      } catch (e) {
        console.error("Failed to optimize", e);
        setEcoMode(false);
        setScheduleData(null);
        showToast("Optimization failed: " + (e.message || "Network Error"));
      }
    } else {
      setScheduleData(null);
    }
  };

  const askCopilot = async () => {
    if (!copilotQuery.trim()) return;
    setIsChatLoading(true);
    setChatResponse("");
    try {
      // Inject context into the user's prompt so Gemini knows how we map to the PS
      const contextPrefix = `[Context: I am viewing the EcoGrid AI dashboard which solves the 4 PS features: Energy Consumption Tracking, Renewable Energy Optimization, Carbon Footprint Monitoring, and Smart Grid Integration.]\n\nUser Question: `;
      const res = await fetch("http://localhost:8000/api/v1/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: contextPrefix + copilotQuery })
      });
      const data = await res.json();
      setChatResponse(data.reply);
      setCopilotQuery("");
    } catch (e) {
      setChatResponse("Error connecting to backend API.");
    } finally {
      setIsChatLoading(false);
    }
  };

  return (
    <div className="flex h-screen bg-[#f8fafc] text-slate-800 font-sans overflow-hidden relative">
      
      {/* Toast Notification System */}
      {toastMessage && (
        <div className="absolute top-6 left-1/2 transform -translate-x-1/2 bg-slate-800 text-white px-6 py-3 rounded-full shadow-2xl z-[100] flex items-center gap-3 animate-fade-in-down">
          <Info className="w-5 h-5 text-blue-400" />
          <span className="font-medium text-sm">{toastMessage}</span>
        </div>
      )}

      {/* Sidebar */}
      <div className="w-20 bg-white border-r border-slate-200 flex flex-col items-center py-6 justify-between shrink-0 z-50 shadow-sm">
        <div className="flex flex-col items-center gap-6">
          <div className="w-10 h-10 rounded-full bg-emerald-500 flex items-center justify-center shadow-lg shadow-emerald-200 cursor-pointer" onClick={() => showToast("EcoGrid AI Dashboard")}>
            <Leaf className="text-white w-6 h-6" />
          </div>
          <div className="flex flex-col gap-3 mt-2 w-full px-3">
            <button onClick={() => setActiveTab('dashboard')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'dashboard' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Overview">
              <Grid className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('energy_flow')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'energy_flow' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Energy Flow">
              <Zap className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('forecasts')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'forecasts' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Forecasts">
              <BarChart3 className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('optimization')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'optimization' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Optimization">
              <BatteryCharging className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('battery')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'battery' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Battery Management">
              <Battery className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('smart_grid')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'smart_grid' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Smart Grid">
              <Power className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('devices')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'devices' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Device Management">
              <MonitorSmartphone className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('sustainability')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'sustainability' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Sustainability">
              <Leaf className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('cost')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'cost' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Cost & Tariff Analytics">
              <DollarSign className="w-5 h-5" />
            </button>
            <button onClick={() => setActiveTab('alerts')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'alerts' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Alerts">
              <Bell className="w-5 h-5" />
            </button>
          </div>
        </div>
        <div className="flex flex-col gap-4 w-full px-3">
          <button onClick={() => setActiveTab('settings')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'settings' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Settings">
            <Settings className="w-5 h-5" />
          </button>
          <button onClick={() => setActiveTab('help')} className={`p-3 rounded-xl transition-colors flex justify-center ${activeTab === 'help' ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50'}`} title="Help">
            <HelpCircle className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col h-full overflow-y-auto">
        
        {/* Header */}
        <header className="h-20 bg-white/80 backdrop-blur-md flex items-center justify-between px-10 border-b border-slate-200/50 sticky top-0 z-40">
          <div className="flex flex-col gap-1">
            <h1 className="text-xl font-bold tracking-tight text-slate-800">EcoGrid AI</h1>
            <div className="flex items-center gap-4">
              <span className="text-xs text-emerald-600 font-medium">Green Energy Management Hackathon Solution</span>
              {/* Hardware Mode Badge */}
              <div className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest ${liveData.mode === 'hardware' ? 'bg-emerald-500/20 text-emerald-600 border border-emerald-500/30' : 'bg-slate-200 text-slate-500'}`}>
                {liveData.mode === 'hardware' ? '● Hardware Connected' : 'Simulation Mode'}
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-6">
            <div className="relative">
              <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400" />
              <input 
                type="text" 
                placeholder="Search microgrid data..." 
                className="pl-10 pr-4 py-2 bg-white rounded-full border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-400 w-64 transition-all"
                onKeyDown={(e) => {
                  if(e.key === 'Enter') {
                    showToast(`Searching for "${e.target.value}" across system logs...`);
                    e.target.value = "";
                  }
                }}
              />
            </div>
            <button 
              onClick={() => setActiveTab('alerts')} 
              className={`relative p-2 rounded-full border transition-colors cursor-pointer ${activeTab === 'alerts' ? 'bg-emerald-50 text-emerald-600 border-emerald-200' : 'text-slate-400 hover:text-slate-600 bg-white border-slate-200'}`}
              title="System Alerts"
            >
              <Bell className="w-4 h-4" />
              {backendAlerts.length > 0 && (
                <span className="absolute top-0 right-0 w-2 h-2 bg-red-500 rounded-full border-2 border-white animate-pulse"></span>
              )}
            </button>
            <div 
              onClick={() => setActiveTab('settings')} 
              className={`w-9 h-9 rounded-full flex items-center justify-center border cursor-pointer transition-colors ${activeTab === 'settings' ? 'bg-blue-200 border-blue-300' : 'bg-blue-100 hover:bg-blue-200 border-slate-200'}`}
              title="User Profile & Settings"
            >
              <User className="w-5 h-5 text-blue-500" />
            </div>
          </div>
        </header>

        {/* Dashboard Grid (Executive Overview) */}
        {activeTab === 'dashboard' && (
        <div className="p-10 flex flex-col gap-8">
          
          <div className="flex justify-between items-end">
            <div>
              <h2 className="text-2xl font-bold text-slate-800">Executive Overview</h2>
              <p className="text-slate-500 mt-1">High-level summary of your microgrid performance today.</p>
            </div>
            <div className="bg-white px-4 py-2 rounded-xl shadow-sm border border-slate-200 text-sm font-semibold flex items-center gap-2">
               <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></div> Live System Status: Nominal
            </div>
          </div>

          {/* Top Row KPIs */}
          <div className="grid grid-cols-4 gap-6">
            <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex items-center justify-between">
              <div>
                <div className="text-sm text-slate-500 font-medium mb-1 flex items-center">
                  Campus Demand
                  <ExplainTooltip position="left" text="Real-time instantaneous power consumed by all buildings and facilities in the microgrid. Measured in kilowatts (kW).">
                    <Info className="w-3.5 h-3.5 text-slate-400 hover:text-slate-600 transition-colors" />
                  </ExplainTooltip>
                </div>
                <p className="text-3xl font-bold text-slate-800">{liveData.demand_kw.toFixed(1)} <span className="text-lg font-medium text-slate-400">kW</span></p>
              </div>
              <div className="w-12 h-12 bg-indigo-50 rounded-2xl flex items-center justify-center text-indigo-500">
                <BarChart3 className="w-6 h-6" />
              </div>
            </div>

            <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex items-center justify-between">
              <div>
                <div className="text-sm text-slate-500 font-medium mb-1 flex items-center">
                  Solar Generation
                  <ExplainTooltip text="Real-time power being generated by the campus solar PV array (kW). Depends on current weather and solar irradiance.">
                    <Info className="w-3.5 h-3.5 text-slate-400 hover:text-slate-600 transition-colors" />
                  </ExplainTooltip>
                </div>
                <p className="text-3xl font-bold text-slate-800">{liveData.solar_kw.toFixed(1)} <span className="text-lg font-medium text-slate-400">kW</span></p>
              </div>
              <div className="w-12 h-12 bg-amber-50 rounded-2xl flex items-center justify-center text-amber-500">
                <Zap className="w-6 h-6" />
              </div>
            </div>

            <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex items-center justify-between">
              <div>
                <div className="text-sm text-slate-500 font-medium mb-1 flex items-center">
                  Grid Import
                  <ExplainTooltip text="Power currently being drawn from the external utility grid. If negative, power is being exported back to the grid.">
                    <Info className="w-3.5 h-3.5 text-slate-400 hover:text-slate-600 transition-colors" />
                  </ExplainTooltip>
                </div>
                <p className="text-3xl font-bold text-slate-800">{liveData.grid_import_kw.toFixed(1)} <span className="text-lg font-medium text-slate-400">kW</span></p>
              </div>
              <div className="w-12 h-12 bg-slate-50 rounded-2xl flex items-center justify-center text-slate-500">
                <Power className="w-6 h-6" />
              </div>
            </div>

            <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex items-center justify-between">
              <div>
                <div className="text-sm text-slate-500 font-medium mb-1 flex items-center">
                  Battery SOC
                  <ExplainTooltip position="right" text="State of Charge (SOC) of the central battery storage system (%). Determines available energy capacity.">
                    <Info className="w-3.5 h-3.5 text-slate-400 hover:text-slate-600 transition-colors" />
                  </ExplainTooltip>
                </div>
                <p className="text-3xl font-bold text-slate-800">{liveData.battery_soc_percent.toFixed(1)}<span className="text-lg font-medium text-slate-400">%</span></p>
              </div>
              <div className="w-12 h-12 bg-emerald-50 rounded-2xl flex items-center justify-center text-emerald-500">
                <Battery className="w-6 h-6" />
              </div>
            </div>
          </div>

          {/* Middle Row: Energy Mix Trend */}
          <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 flex-1 min-h-[350px] flex flex-col">
             <div className="flex justify-between items-center mb-6">
               <div className="flex items-center gap-4">
                 <div className="font-bold text-slate-800 flex items-center gap-2">Energy Mix {energyTimeRange === 'day' ? '(kW)' : '(kWh/day)'} <ExplainTooltip position="left" text={energyTimeRange === 'day' ? "Historical comparison of solar power generation versus total campus power demand over 24 hours." : "Daily total solar energy generation versus campus energy consumption over the selected period."}><Info className="w-4 h-4 text-slate-400" /></ExplainTooltip></div>
                 <div className="bg-slate-100 p-1 rounded-xl flex gap-1 text-xs font-semibold">
                   <button onClick={() => setEnergyTimeRange('day')} className={`px-3 py-1.5 rounded-lg transition-colors ${energyTimeRange === 'day' ? 'bg-white shadow-sm text-slate-800' : 'text-slate-500 hover:text-slate-700'}`}>24h</button>
                   <button onClick={() => setEnergyTimeRange('week')} className={`px-3 py-1.5 rounded-lg transition-colors ${energyTimeRange === 'week' ? 'bg-white shadow-sm text-slate-800' : 'text-slate-500 hover:text-slate-700'}`}>Week</button>
                   <button onClick={() => setEnergyTimeRange('month')} className={`px-3 py-1.5 rounded-lg transition-colors ${energyTimeRange === 'month' ? 'bg-white shadow-sm text-slate-800' : 'text-slate-500 hover:text-slate-700'}`}>Month</button>
                 </div>
               </div>
               <div className="flex gap-4 text-xs font-semibold">
                 <div className="flex items-center gap-1"><div className="w-3 h-3 rounded bg-amber-400"></div> Solar</div>
                 <div className="flex items-center gap-1"><div className="w-3 h-3 rounded bg-indigo-500"></div> Demand</div>
               </div>
             </div>
              <div className="flex-1 w-full h-full">
               {energyHistory.length > 0 ? (
                 <ResponsiveContainer width="100%" height="100%">
                   <AreaChart data={energyHistory} margin={{ top: 10, right: 0, left: -20, bottom: 0 }}>
                     <defs>
                       <linearGradient id="colorSolarDbg" x1="0" y1="0" x2="0" y2="1">
                         <stop offset="5%" stopColor="#fbbf24" stopOpacity={0.8}/>
                         <stop offset="95%" stopColor="#fbbf24" stopOpacity={0}/>
                       </linearGradient>
                       <linearGradient id="colorDemandDbg" x1="0" y1="0" x2="0" y2="1">
                         <stop offset="5%" stopColor="#6366f1" stopOpacity={0.1}/>
                         <stop offset="95%" stopColor="#6366f1" stopOpacity={0}/>
                       </linearGradient>
                     </defs>
                     <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#94a3b8' }} dy={10} />
                     <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#94a3b8' }} />
                     <Tooltip 
                       cursor={{stroke: '#e2e8f0', strokeWidth: 1, strokeDasharray: '4 4'}} 
                       contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} 
                       formatter={(value, name) => [`${value} ${energyTimeRange === 'day' ? 'kW' : 'kWh'}`, name === 'solar' ? 'Solar PV' : 'Campus Demand']}
                     />
                     <Area type="monotone" dataKey="demand" stroke="#6366f1" strokeWidth={3} fillOpacity={1} fill="url(#colorDemandDbg)" />
                     <Area type="monotone" dataKey="solar" stroke="#fbbf24" strokeWidth={3} fillOpacity={1} fill="url(#colorSolarDbg)" />
                   </AreaChart>
                 </ResponsiveContainer>
               ) : (
                 <div className="w-full h-full flex items-center justify-center text-slate-400 text-sm">
                   Loading Trend Data...
                 </div>
               )}
              </div>
          </div>

          {/* AI Copilot Section (Full Width Bottom) */}
          <div className="bg-slate-900 rounded-3xl p-8 text-white shadow-xl flex gap-8 items-center border border-slate-800 relative overflow-hidden">
             <div className="absolute -right-20 -top-20 w-64 h-64 bg-emerald-500 rounded-full blur-[120px] opacity-20"></div>
             
             <div className="w-1/3 z-10">
               <h2 className="text-2xl font-bold mb-2 bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent flex items-center gap-2">
                 EcoGrid AI Copilot
               </h2>
               <p className="text-slate-400 text-sm mb-4">Powered by Google Gemma-4 (31B)</p>
               <input 
                 type="text"
                 value={copilotQuery}
                 onChange={(e) => setCopilotQuery(e.target.value)}
                 onKeyDown={(e) => e.key === 'Enter' && askCopilot()}
                 placeholder="Ask about your Carbon Footprint..." 
                 className="w-full bg-slate-800 border border-slate-700 rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-emerald-500 transition-colors placeholder:text-slate-500"
               />
               <button 
                 onClick={askCopilot}
                 disabled={isChatLoading}
                 className="mt-3 w-full bg-emerald-600 hover:bg-emerald-500 text-white py-2.5 rounded-xl text-sm font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
               >
                 {isChatLoading ? "Gemini is analyzing the grid..." : "Ask AI"}
               </button>
             </div>

             <div className="w-2/3 h-full bg-slate-800/50 border border-slate-700 rounded-2xl p-6 text-sm text-slate-300 leading-relaxed overflow-y-auto max-h-48 z-10 shadow-inner">
                {chatResponse || (
                  <div className="flex flex-col gap-2">
                    <p className="text-emerald-400 font-semibold">Ready to assist, Facility Manager.</p>
                    <p>I am actively monitoring your <span className="text-white">Energy Consumption</span>, optimizing <span className="text-white">Renewable Storage</span>, and tracking <span className="text-white">Carbon Footprint</span>.</p>
                    <p className="text-slate-400 mt-2 italic">Try asking: "How much CO2 did we offset with solar today?" or "Why did the OR-Tools optimizer decide to charge the battery now?"</p>
                  </div>
                )}
             </div>
          </div>
        </div>
        )}

        {/* Energy Flow Page */}
        {activeTab === 'energy_flow' && (
          <div className="p-10 flex-1 flex flex-col">
            <h2 className="text-2xl font-bold text-slate-800 mb-6">Microgrid Energy Flow</h2>
            <div className="bg-slate-900 rounded-[40px] p-8 shadow-2xl border border-slate-800 flex-1 flex items-center justify-center relative overflow-hidden">
              <div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'radial-gradient(#475569 2px, transparent 2px)', backgroundSize: '40px 40px' }}></div>
              
              <div className="relative w-full max-w-5xl aspect-[16/9]">
                {/* SVG Connections */}
                <svg viewBox="0 0 1000 562" className="absolute inset-0 w-full h-full pointer-events-none z-10" style={{ filter: 'drop-shadow(0 0 8px rgba(0,0,0,0.5))' }}>
                  <defs>
                    <linearGradient id="glowSolar" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#fbbf24" /><stop offset="100%" stopColor="#10b981" /></linearGradient>
                    <linearGradient id="glowGrid" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#94a3b8" /><stop offset="100%" stopColor="#64748b" /></linearGradient>
                    <linearGradient id="glowBattery" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#3b82f6" /><stop offset="100%" stopColor="#10b981" /></linearGradient>
                    <linearGradient id="glowCampus" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#10b981" /><stop offset="100%" stopColor="#6366f1" /></linearGradient>
                  </defs>
                  
                  {/* Solar -> Hub */}
                  <path id="path-solar" d="M 200 140 C 350 140, 350 281, 500 281" fill="none" stroke="url(#glowSolar)" strokeWidth="3" className="opacity-40" strokeDasharray="6 6" />
                  <circle r="6" fill="#fbbf24" style={{ filter: 'drop-shadow(0 0 6px #fbbf24)' }}>
                    {liveData.solar_kw > 0 && <animateMotion dur="2s" repeatCount="indefinite"><mpath href="#path-solar" /></animateMotion>}
                  </circle>

                  {/* Hub <-> Grid */}
                  <path id="path-grid" d={liveData.grid_import_kw > 0 ? "M 800 140 C 650 140, 650 281, 500 281" : "M 500 281 C 650 281, 650 140, 800 140"} fill="none" stroke="url(#glowGrid)" strokeWidth="3" className="opacity-40" strokeDasharray="6 6" />
                  <circle r="6" fill="#94a3b8" style={{ filter: 'drop-shadow(0 0 6px #94a3b8)' }}>
                    <animateMotion dur="2.5s" repeatCount="indefinite"><mpath href="#path-grid" /></animateMotion>
                  </circle>

                  {/* Hub <-> Battery */}
                  {/* Assuming liveData.battery_soc_percent changes are abstract, we animate based on typical flow. For demo, we just animate to hub */}
                  <path id="path-battery" d="M 200 422 C 350 422, 350 281, 500 281" fill="none" stroke="url(#glowBattery)" strokeWidth="3" className="opacity-40" strokeDasharray="6 6" />
                  <circle r="6" fill="#3b82f6" style={{ filter: 'drop-shadow(0 0 6px #3b82f6)' }}>
                    <animateMotion dur="3s" repeatCount="indefinite"><mpath href="#path-battery" /></animateMotion>
                  </circle>

                  {/* Hub -> Campus */}
                  <path id="path-campus" d="M 500 281 C 650 281, 650 422, 800 422" fill="none" stroke="url(#glowCampus)" strokeWidth="3" className="opacity-40" strokeDasharray="6 6" />
                  <circle r="6" fill="#6366f1" style={{ filter: 'drop-shadow(0 0 6px #6366f1)' }}>
                    <animateMotion dur="1.5s" repeatCount="indefinite"><mpath href="#path-campus" /></animateMotion>
                  </circle>
                </svg>

                {/* Nodes */}
                {/* Solar */}
                <div className="absolute top-[25%] left-[20%] -translate-x-1/2 -translate-y-1/2 z-20 flex flex-col items-center group">
                  <div className="w-24 h-24 bg-slate-800/80 backdrop-blur-md border border-amber-500/50 rounded-2xl flex flex-col items-center justify-center shadow-[0_0_30px_rgba(251,191,36,0.15)] group-hover:shadow-[0_0_40px_rgba(251,191,36,0.3)] transition-all">
                     <Zap className="w-10 h-10 text-amber-400 mb-1" />
                  </div>
                  <div className="bg-slate-800 border border-slate-700 px-4 py-2 rounded-xl mt-4 shadow-xl text-center">
                    <div className="font-bold text-slate-300 text-sm flex items-center justify-center gap-1">Solar PV <ExplainTooltip position="left" text="Total current electricity produced by the solar panels."><Info className="w-3.5 h-3.5 text-slate-500" /></ExplainTooltip></div>
                    <p className="text-amber-400 font-bold text-lg">{liveData.solar_kw.toFixed(1)} kW</p>
                  </div>
                </div>

                {/* Grid */}
                <div className="absolute top-[25%] left-[80%] -translate-x-1/2 -translate-y-1/2 z-20 flex flex-col items-center group">
                  <div className="w-24 h-24 bg-slate-800/80 backdrop-blur-md border border-slate-500/50 rounded-2xl flex flex-col items-center justify-center shadow-[0_0_30px_rgba(148,163,184,0.15)] group-hover:shadow-[0_0_40px_rgba(148,163,184,0.3)] transition-all">
                     <Power className="w-10 h-10 text-slate-400 mb-1" />
                  </div>
                  <div className="bg-slate-800 border border-slate-700 px-4 py-2 rounded-xl mt-4 shadow-xl text-center">
                    <div className="font-bold text-slate-300 text-sm flex items-center justify-center gap-1">Utility Grid <ExplainTooltip position="right" text="Net power drawn from or exported to the main city power grid."><Info className="w-3.5 h-3.5 text-slate-500" /></ExplainTooltip></div>
                    <p className="text-slate-300 font-bold text-lg">{liveData.grid_import_kw > 0 ? `${liveData.grid_import_kw.toFixed(1)} kW In` : `${liveData.grid_export_kw.toFixed(1)} kW Out`}</p>
                  </div>
                </div>

                {/* Hub */}
                <div className="absolute top-[50%] left-[50%] -translate-x-1/2 -translate-y-1/2 z-30 flex flex-col items-center">
                  <div className="w-36 h-36 bg-emerald-500/10 backdrop-blur-xl border border-emerald-400 rounded-full flex flex-col items-center justify-center shadow-[0_0_60px_rgba(16,185,129,0.3)] animate-pulse">
                     <div className="w-24 h-24 bg-emerald-500 rounded-full flex items-center justify-center shadow-inner">
                       <Grid className="w-12 h-12 text-white" />
                     </div>
                  </div>
                  <div className="bg-emerald-900/50 border border-emerald-500/50 px-5 py-2 rounded-full mt-6 shadow-xl backdrop-blur-md">
                    <span className="text-emerald-400 font-bold tracking-widest text-xs uppercase">AI Energy Hub</span>
                  </div>
                </div>

                {/* Battery */}
                <div className="absolute top-[75%] left-[20%] -translate-x-1/2 -translate-y-1/2 z-20 flex flex-col items-center group">
                  <div className="w-24 h-24 bg-slate-800/80 backdrop-blur-md border border-blue-500/50 rounded-2xl flex flex-col items-center justify-center shadow-[0_0_30px_rgba(59,130,246,0.15)] group-hover:shadow-[0_0_40px_rgba(59,130,246,0.3)] transition-all">
                     <Battery className="w-10 h-10 text-blue-400 mb-1" />
                  </div>
                  <div className="bg-slate-800 border border-slate-700 px-4 py-2 rounded-xl mt-4 shadow-xl text-center">
                    <div className="font-bold text-slate-300 text-sm flex items-center justify-center gap-1">BESS Storage <ExplainTooltip position="left" text="Battery Energy Storage System level."><Info className="w-3.5 h-3.5 text-slate-500" /></ExplainTooltip></div>
                    <p className="text-blue-400 font-bold text-lg">{liveData.battery_soc_percent.toFixed(1)}%</p>
                  </div>
                </div>

                {/* Campus Loads */}
                <div className="absolute top-[75%] left-[80%] -translate-x-1/2 -translate-y-1/2 z-20 flex flex-col items-center group">
                  <div className="w-24 h-24 bg-slate-800/80 backdrop-blur-md border border-indigo-500/50 rounded-2xl flex flex-col items-center justify-center shadow-[0_0_30px_rgba(99,102,241,0.15)] group-hover:shadow-[0_0_40px_rgba(99,102,241,0.3)] transition-all">
                     <BarChart3 className="w-10 h-10 text-indigo-400 mb-1" />
                  </div>
                  <div className="bg-slate-800 border border-slate-700 px-4 py-2 rounded-xl mt-4 shadow-xl text-center">
                    <div className="font-bold text-slate-300 text-sm flex items-center justify-center gap-1">Campus Loads <ExplainTooltip position="right" text="Total power currently being drawn by all campus facilities."><Info className="w-3.5 h-3.5 text-slate-500" /></ExplainTooltip></div>
                    <p className="text-indigo-400 font-bold text-lg">{liveData.demand_kw.toFixed(1)} kW</p>
                  </div>
                </div>

              </div>
            </div>
          </div>
        )}

        {/* Forecasts Page */}
        {activeTab === 'forecasts' && (
          <div className="p-10 flex flex-col gap-8">
            <div>
              <h2 className="text-2xl font-bold text-slate-800">24-Hour AI Forecasts</h2>
              <p className="text-slate-500 mt-1">XGBoost machine learning predictions for the upcoming day.</p>
            </div>
            
            <div className="grid grid-cols-2 gap-8">
              {/* Solar Forecast */}
              <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100">
                <div className="font-bold text-slate-800 mb-6 flex items-center gap-2"><Zap className="w-5 h-5 text-amber-500"/> Solar Generation Forecast (kW) <ExplainTooltip text="Predicted solar power output over the next 24 hours based on weather data and historical patterns."><Info className="w-4 h-4 text-slate-400 ml-2" /></ExplainTooltip></div>
                <div className="h-64">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={forecastData}>
                      <XAxis dataKey="name" fontSize={12} tickLine={false} axisLine={false} />
                      <YAxis fontSize={12} tickLine={false} axisLine={false} />
                      <Tooltip cursor={{fill: '#f1f5f9'}} contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                      <Bar dataKey="Production" fill="#fbbf24" radius={[4, 4, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>

              {/* Demand Forecast */}
              <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100">
                <div className="font-bold text-slate-800 mb-6 flex items-center gap-2"><BarChart3 className="w-5 h-5 text-indigo-500"/> Campus Demand Forecast (kW) <ExplainTooltip text="Predicted campus energy usage over the next 24 hours based on historical usage and schedules."><Info className="w-4 h-4 text-slate-400 ml-2" /></ExplainTooltip></div>
                <div className="h-64">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={forecastData}>
                      <XAxis dataKey="name" fontSize={12} tickLine={false} axisLine={false} />
                      <YAxis fontSize={12} tickLine={false} axisLine={false} />
                      <Tooltip cursor={{fill: '#f1f5f9'}} contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                      <Bar dataKey="Usage" fill="#6366f1" radius={[4, 4, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Optimization Page */}
        {activeTab === 'optimization' && (
          <div className="p-10 flex flex-col gap-8">
            <div className="flex justify-between items-center">
              <div>
                <h2 className="text-2xl font-bold text-slate-800">Mathematical Optimization</h2>
                <p className="text-slate-500 mt-1">Google OR-Tools based cost and carbon minimization.</p>
              </div>
              
              <div className="flex items-center gap-4 bg-white px-5 py-3 rounded-2xl border border-slate-200 shadow-sm">
                <span className="text-sm font-semibold text-slate-700">AI Optimization Engine</span>
                <button 
                  onClick={toggleEcoMode}
                  className={`relative inline-flex h-7 w-14 items-center rounded-full transition-colors focus:outline-none ${ecoMode ? 'bg-emerald-500' : 'bg-slate-300'}`}
                >
                  <span className={`inline-block h-5 w-5 transform rounded-full bg-white transition-transform ${ecoMode ? 'translate-x-8' : 'translate-x-1'}`} />
                </button>
              </div>
            </div>

            {!ecoMode ? (
              <div className="bg-slate-50 rounded-3xl p-12 border border-slate-200 text-center flex flex-col items-center justify-center">
                 <BatteryCharging className="w-16 h-16 text-slate-400 mb-4" />
                 <h3 className="text-xl font-bold text-slate-700">Optimization Disabled</h3>
                 <p className="text-slate-500 mt-2 max-w-md">Enable the AI Optimization Engine to mathematically schedule battery storage and flexible loads for maximum efficiency.</p>
              </div>
            ) : scheduleData && scheduleData.status === "OPTIMAL" ? (
              <OptimizationResults scheduleData={scheduleData} forecastData={forecastData} />
            ) : (
              <div className="bg-white rounded-3xl p-12 border border-slate-100 text-center shadow-sm">
                <div className="w-8 h-8 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
                <p className="text-slate-500 font-medium">Running OR-Tools Simplex algorithm...</p>
              </div>
            )}
          </div>
        )}

        {/* Smart Grid Page */}
        {activeTab === 'smart_grid' && (
          <div className="p-10 flex flex-col gap-8">
            <div className="flex justify-between items-center">
              <div>
                <h2 className="text-2xl font-bold text-slate-800">Smart Grid Controls & Demo</h2>
                <p className="text-slate-500 mt-1">IoT Device Management and What-If Scenario Simulation.</p>
              </div>
              <div className={`px-4 py-2 rounded-full text-xs font-bold uppercase tracking-widest ${liveData.mode === 'hardware' ? 'bg-emerald-100 text-emerald-700 border border-emerald-200' : 'bg-slate-200 text-slate-600'}`}>
                {liveData.mode === 'hardware' ? '● Hardware Connected' : 'Simulation Mode'}
              </div>
            </div>

            <div className="grid grid-cols-12 gap-8">
              
              {/* Manual Device Overrides */}
              <div className="col-span-8 bg-white rounded-3xl p-8 shadow-sm border border-slate-100">
                <h3 className="font-bold text-slate-800 mb-6">Flexible Load Management</h3>
                <div className="grid grid-cols-2 gap-6">
                  
                  {/* Smart HVAC Device */}
                  <div className={`border ${liveData.loads.hvac.status === 'running' ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-slate-50'} rounded-2xl p-6 flex flex-col justify-between transition-all relative`}>
                    <div className="flex justify-between items-start mb-6">
                      <div className={`w-14 h-14 rounded-xl flex items-center justify-center transition-colors ${liveData.loads.hvac.status === 'running' ? 'bg-emerald-100 text-emerald-600' : 'bg-white border border-slate-200 text-slate-400'}`}>
                        <Wind className="w-7 h-7" />
                      </div>
                      <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${ecoMode ? 'bg-purple-100 text-purple-700' : 'bg-slate-200 text-slate-600'}`}>
                        {ecoMode ? 'AI Controlled' : 'Manual'}
                      </span>
                    </div>
                    <div>
                      <div className="font-bold text-lg text-slate-800 flex items-center justify-between">Smart HVAC <ExplainTooltip position="left" text="Heating, Ventilation, and Air Conditioning unit. Classified as a flexible load because its operation can be shifted by AI to save costs."><Info className="w-4 h-4 text-slate-400" /></ExplainTooltip></div>
                      <p className="text-sm text-slate-500 mb-4">Campus Main Hall (28 kW)</p>
                      <button 
                        disabled={ecoMode}
                        className={`w-full py-3 rounded-xl font-bold transition-colors ${ecoMode ? 'bg-slate-200 text-slate-400 cursor-not-allowed' : liveData.loads.hvac.status === 'running' ? 'bg-red-100 text-red-600 hover:bg-red-200' : 'bg-emerald-500 text-white hover:bg-emerald-600'}`}
                        onClick={() => {
                          const action = liveData.loads.hvac.status === 'running' ? 'stop' : 'start';
                          fetch(`http://127.0.0.1:8000/api/v1/simulation/control?device=hvac&action=${action}`, {method: 'POST'});
                        }}
                      >
                        {liveData.loads.hvac.status === 'running' ? 'Force Stop' : 'Force Start'}
                      </button>
                    </div>
                  </div>

                  {/* EV Chargers */}
                  <div className={`border ${liveData.loads.ev.status === 'running' ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-slate-50'} rounded-2xl p-6 flex flex-col justify-between transition-all relative`}>
                    <div className="flex justify-between items-start mb-6">
                      <div className={`w-14 h-14 rounded-xl flex items-center justify-center transition-colors ${liveData.loads.ev.status === 'running' ? 'bg-emerald-100 text-emerald-600' : 'bg-white border border-slate-200 text-slate-400'}`}>
                        <Zap className="w-7 h-7" />
                      </div>
                      <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${ecoMode ? 'bg-purple-100 text-purple-700' : 'bg-slate-200 text-slate-600'}`}>
                        {ecoMode ? 'AI Controlled' : 'Manual'}
                      </span>
                    </div>
                    <div>
                      <div className="font-bold text-lg text-slate-800 flex items-center justify-between">EV Fleet Chargers <ExplainTooltip position="right" text="Electric Vehicle charging stations. The AI schedules charging during off-peak hours or high solar generation."><Info className="w-4 h-4 text-slate-400" /></ExplainTooltip></div>
                      <p className="text-sm text-slate-500 mb-4">Parking Lot A (40 kW)</p>
                      <button 
                        disabled={ecoMode}
                        className={`w-full py-3 rounded-xl font-bold transition-colors ${ecoMode ? 'bg-slate-200 text-slate-400 cursor-not-allowed' : liveData.loads.ev.status === 'running' ? 'bg-red-100 text-red-600 hover:bg-red-200' : 'bg-emerald-500 text-white hover:bg-emerald-600'}`}
                        onClick={() => {
                          const action = liveData.loads.ev.status === 'running' ? 'stop' : 'start';
                          fetch(`http://127.0.0.1:8000/api/v1/simulation/control?device=ev&action=${action}`, {method: 'POST'});
                        }}
                      >
                        {liveData.loads.ev.status === 'running' ? 'Force Stop' : 'Force Start'}
                      </button>
                    </div>
                  </div>

                </div>
              </div>

              {/* What-If Demo Scenarios */}
              <div className="col-span-4 bg-white rounded-3xl p-8 shadow-sm border border-slate-100">
                <div className="font-bold text-slate-800 mb-6 flex items-center gap-2"><Power className="w-5 h-5 text-indigo-500"/> Demo Scenarios <ExplainTooltip text="Hardware-in-the-loop triggers to test how the system reacts to environmental and load changes."><Info className="w-4 h-4 text-slate-400 ml-2" /></ExplainTooltip></div>
                <p className="text-sm text-slate-500 mb-6">Trigger environmental changes to demonstrate AI responsiveness.</p>
                
                <div className="flex flex-col gap-3">
                  <button 
                    className="w-full text-left px-5 py-4 border border-slate-200 rounded-2xl hover:border-indigo-300 hover:bg-indigo-50 transition-colors font-semibold text-slate-700 flex justify-between items-center"
                    onClick={() => {
                      fetch(`http://127.0.0.1:8000/api/v1/simulation/control?device=hvac&action=start`, {method: 'POST'});
                      showToast("Simulating Evening Peak Demand!");
                    }}
                  >
                    Evening Peak Surge <Zap className="w-4 h-4 text-slate-400" />
                  </button>
                  <button 
                    className="w-full text-left px-5 py-4 border border-slate-200 rounded-2xl hover:border-amber-300 hover:bg-amber-50 transition-colors font-semibold text-slate-700 flex justify-between items-center"
                    onClick={() => {
                      showToast("Simulating Cloud Cover! Solar generation dropping.");
                    }}
                  >
                    Sudden Cloud Cover <CloudRain className="w-4 h-4 text-slate-400" />
                  </button>
                  <button 
                    className="w-full text-left px-5 py-4 border border-emerald-200 bg-emerald-50 rounded-2xl hover:bg-emerald-100 transition-colors font-bold text-emerald-800 flex justify-between items-center shadow-sm"
                    onClick={() => {
                      fetch(`http://127.0.0.1:8000/api/v1/simulation/reset`, {method: 'POST'});
                      showToast("Resetting Simulator to Baseline.");
                    }}
                  >
                    Reset Simulator <Grid className="w-4 h-4 text-emerald-500" />
                  </button>
                </div>
              </div>

            </div>
          </div>
        )}

        {/* Sustainability Page */}
        {activeTab === 'sustainability' && (
          <div className="p-10 flex flex-col gap-8">
            <div className="flex justify-between items-center">
              <div>
                <h2 className="text-2xl font-bold text-slate-800">Carbon & Sustainability</h2>
                <p className="text-slate-500 mt-1">Scope 2 emissions tracking and renewable utilization.</p>
              </div>
              <div className="bg-emerald-100 text-emerald-800 px-4 py-2 rounded-xl border border-emerald-200 font-bold flex items-center gap-2">
                 <CloudRain className="w-5 h-5" />
                 Green Efficiency Score: 92/100
              </div>
            </div>
            
            <div className="grid grid-cols-3 gap-8">
               <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 relative flex flex-col justify-between h-48">
                 <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-50 rounded-full blur-3xl -mr-10 -mt-10"></div>
                 <div className="font-bold text-slate-800 relative z-10 flex items-center gap-2"><CloudRain className="w-5 h-5 text-emerald-500"/> Total CO₂ Avoided <ExplainTooltip position="left" text="Carbon emissions prevented by using solar and battery power instead of grid power."><Info className="w-4 h-4 text-slate-400 ml-2" /></ExplainTooltip></div>
                 <div className="relative z-10">
                   <p className="text-4xl font-bold text-slate-800">1,245 <span className="text-xl font-medium text-slate-500">kg</span></p>
                   <p className="text-sm font-semibold text-emerald-500 mt-2">↑ 12% this month</p>
                 </div>
               </div>

               <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 relative flex flex-col justify-between h-48">
                 <div className="absolute top-0 right-0 w-32 h-32 bg-amber-50 rounded-full blur-3xl -mr-10 -mt-10"></div>
                 <div className="font-bold text-slate-800 relative z-10 flex items-center gap-2"><Zap className="w-5 h-5 text-amber-500"/> Renewable Utilization <ExplainTooltip text="Percentage of total campus energy demand that was met entirely by on-site renewable energy."><Info className="w-4 h-4 text-slate-400 ml-2" /></ExplainTooltip></div>
                 <div className="relative z-10">
                   <p className="text-4xl font-bold text-slate-800">68<span className="text-xl font-medium text-slate-500">%</span></p>
                   <p className="text-sm font-semibold text-amber-600 mt-2">Target: 80%</p>
                 </div>
               </div>

               <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 relative flex flex-col justify-between h-48">
                 <div className="absolute top-0 right-0 w-32 h-32 bg-blue-50 rounded-full blur-3xl -mr-10 -mt-10"></div>
                 <div className="font-bold text-slate-800 relative z-10 flex items-center gap-2"><BarChart3 className="w-5 h-5 text-blue-500"/> Current Carbon Intensity <ExplainTooltip position="right" text="The average amount of CO2 emitted per kWh of electricity drawn from the local utility grid."><Info className="w-4 h-4 text-slate-400 ml-2" /></ExplainTooltip></div>
                 <div className="relative z-10">
                   <p className="text-4xl font-bold text-slate-800">420 <span className="text-xl font-medium text-slate-500">g/kWh</span></p>
                   <p className="text-sm font-semibold text-slate-500 mt-2">Local Grid Average</p>
                 </div>
               </div>
            </div>

            <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 flex-1 flex flex-col">
              <div className="font-bold text-slate-800 mb-6 flex items-center gap-2">Monthly Carbon Savings Trend (kg CO₂) <ExplainTooltip text="Historical tracking of scope 2 emission reductions achieved by the EcoGrid system."><Info className="w-4 h-4 text-slate-400 ml-2" /></ExplainTooltip></div>
              <div className="h-64 rounded-2xl flex items-center justify-center">
                 <ResponsiveContainer width="100%" height="100%">
                   <LineChart data={historicalCarbonData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                     <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#94a3b8' }} dy={10} />
                     <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#94a3b8' }} />
                     <Tooltip 
                       cursor={{stroke: '#e2e8f0', strokeWidth: 2}} 
                       contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)', fontSize: '12px', fontWeight: 'bold' }} 
                     />
                     <Line type="monotone" dataKey="savings" stroke="#10b981" strokeWidth={4} dot={{r: 6, fill: '#10b981', stroke: '#fff', strokeWidth: 2}} activeDot={{r: 8}} />
                   </LineChart>
                 </ResponsiveContainer>
              </div>
            </div>
          </div>
        )}

        {/* Alerts Page */}
        {activeTab === 'alerts' && (
          <div className="p-10 flex flex-col gap-8 h-full">
            <h2 className="text-2xl font-bold text-slate-800">System Alerts & Logs</h2>
            <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 overflow-hidden flex flex-col">
              <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50">
                 <h3 className="font-bold text-slate-700">Recent Activity</h3>
                 <span className="bg-slate-200 text-slate-600 px-3 py-1 rounded-full text-xs font-bold">{backendAlerts.length} Events</span>
              </div>
              <div className="p-6 overflow-y-auto flex-1 flex flex-col gap-4">
                {backendAlerts.length > 0 ? backendAlerts.map((alert, idx) => (
                  <div key={idx} className={`p-4 rounded-2xl border flex items-start gap-4 ${
                    alert.type === 'CRITICAL' ? 'bg-red-50 border-red-100 text-red-800' :
                    alert.type === 'WARNING' ? 'bg-orange-50 border-orange-100 text-orange-800' :
                    'bg-blue-50 border-blue-100 text-blue-800'
                  }`}>
                    <div className="mt-1">
                       {alert.type === 'CRITICAL' ? <AlertCircle className="w-5 h-5 shrink-0 text-red-500" /> : <Info className="w-5 h-5 shrink-0 text-blue-500" />}
                    </div>
                    <div>
                       <p className="text-sm font-bold">{alert.type}</p>
                       <p className="text-sm mt-1 opacity-90">{alert.msg}</p>
                    </div>
                  </div>
                )) : (
                  <div className="p-12 text-center text-slate-400 flex flex-col items-center justify-center h-full">
                    <CheckCircle className="w-12 h-12 mb-4 text-slate-300" />
                    <p className="font-medium">No alerts recorded.</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Settings Page */}
        {activeTab === 'settings' && (
          <div className="p-10">
            <h2 className="text-2xl font-bold text-slate-800 mb-6">Settings</h2>
            <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 text-center">
              <Settings className="w-16 h-16 text-emerald-500 mx-auto mb-4 opacity-50" />
              <p className="text-slate-500">System configuration options.</p>
            </div>
          </div>
        )}

        {/* Help Page */}
        {activeTab === 'help' && (
          <div className="p-10">
            <h2 className="text-2xl font-bold text-slate-800 mb-6">Help & Documentation</h2>
            <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 text-center">
              <HelpCircle className="w-16 h-16 text-emerald-500 mx-auto mb-4 opacity-50" />
              <p className="text-slate-500">EcoGrid AI architecture & prototype limitations.</p>
            </div>
          </div>
        )}

        {/* Battery Management Page */}
        {activeTab === 'battery' && batteryState && (
          <div className="p-10 flex flex-col gap-8 h-full">
            <h2 className="text-2xl font-bold text-slate-800">Battery Management</h2>
            <div className="grid grid-cols-4 gap-6">
              <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex flex-col justify-between h-40">
                <div className="font-bold text-slate-500 flex items-center justify-between">State of Charge <ExplainTooltip position="left" text="Current energy level of the battery as a percentage of its total capacity."><Info className="w-4 h-4 text-slate-400" /></ExplainTooltip></div>
                <p className="text-4xl font-bold text-slate-800">{Math.round(batteryState.soc)}%</p>
              </div>
              <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex flex-col justify-between h-40">
                <div className="font-bold text-slate-500 flex items-center justify-between">Current Power <ExplainTooltip text="The rate at which energy is currently flowing in (charging) or out (discharging)."><Info className="w-4 h-4 text-slate-400" /></ExplainTooltip></div>
                <p className="text-4xl font-bold text-slate-800">{batteryState.current_power.toFixed(1)} <span className="text-xl">kW</span></p>
              </div>
              <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex flex-col justify-between h-40">
                <div className="font-bold text-slate-500 flex items-center justify-between">Status <ExplainTooltip text="Idle, Charging, or Discharging state managed by the AI optimizer."><Info className="w-4 h-4 text-slate-400" /></ExplainTooltip></div>
                <p className={`text-2xl font-bold ${batteryState.status === 'Charging' ? 'text-emerald-500' : batteryState.status === 'Discharging' ? 'text-amber-500' : 'text-slate-500'}`}>{batteryState.status}</p>
              </div>
              <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex flex-col justify-between h-40">
                <div className="font-bold text-slate-500 flex items-center justify-between">Health (SOH) <ExplainTooltip position="right" text="State of Health. Indicates battery degradation over its lifetime compared to a new battery."><Info className="w-4 h-4 text-slate-400" /></ExplainTooltip></div>
                <p className="text-4xl font-bold text-emerald-500">{batteryState.soh}%</p>
              </div>
            </div>
          </div>
        )}



        {/* Cost Page */}
        {activeTab === 'cost' && tariffData && (
          <div className="p-10 flex flex-col gap-8 h-full">
            <h2 className="text-2xl font-bold text-slate-800">Cost & Tariff Analytics</h2>
            <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 flex-1 flex flex-col">
              <h3 className="font-bold text-slate-800 mb-6">Time-of-Use Tariff Pricing</h3>
              <div className="flex-1 rounded-2xl flex items-center justify-center min-h-[300px]">
                 <ResponsiveContainer width="100%" height="100%">
                   <BarChart data={tariffData.tariffs} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                     <XAxis dataKey="hour" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#94a3b8' }} dy={10} />
                     <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#94a3b8' }} />
                     <Tooltip cursor={{fill: '#f8fafc'}} contentStyle={{ borderRadius: '12px' }}/>
                     <Bar dataKey="price" fill="#10b981" radius={[4, 4, 0, 0]} name="Price (₹/kWh)" />
                   </BarChart>
                 </ResponsiveContainer>
              </div>
            </div>
          </div>
        )}

        {/* Devices Page */}
        {activeTab === 'devices' && (
          <div className="p-10 flex flex-col gap-8 h-full">
            <h2 className="text-2xl font-bold text-slate-800">Device Management</h2>
            <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 overflow-hidden">
              <table className="w-full text-left">
                <thead className="bg-slate-50 border-b border-slate-100">
                  <tr>
                    <th className="p-4 font-bold text-slate-600 text-sm">Device</th>
                    <th className="p-4 font-bold text-slate-600 text-sm">Type</th>
                    <th className="p-4 font-bold text-slate-600 text-sm">Location</th>
                    <th className="p-4 font-bold text-slate-600 text-sm">Status</th>
                    <th className="p-4 font-bold text-slate-600 text-sm">Power (kW)</th>
                  </tr>
                </thead>
                <tbody>
                  {devicesData.map(d => (
                    <tr key={d.id} className="border-b border-slate-50 last:border-0 hover:bg-slate-50">
                      <td className="p-4 font-semibold text-slate-800">{d.name}</td>
                      <td className="p-4 text-slate-500">{d.type}</td>
                      <td className="p-4 text-slate-500">{d.location}</td>
                      <td className="p-4"><span className={`px-2 py-1 rounded text-xs font-bold uppercase ${d.status === 'running' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{d.status}</span></td>
                      <td className="p-4 font-medium text-slate-700">{d.power_kw}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Settings Page */}
        {activeTab === 'settings' && settingsData && (
          <div className="p-10 flex flex-col gap-8 h-full">
            <h2 className="text-2xl font-bold text-slate-800">System Settings</h2>
            <div className="bg-white rounded-3xl shadow-sm border border-slate-100 p-8 max-w-2xl">
              <div className="flex flex-col gap-6">
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-2">Facility Name</label>
                  <input type="text" className="w-full border border-slate-200 rounded-xl px-4 py-2" defaultValue={settingsData.facility_name} />
                </div>
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-2">Battery Capacity (kWh)</label>
                  <input type="number" className="w-full border border-slate-200 rounded-xl px-4 py-2" defaultValue={settingsData.battery_capacity} />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Min SOC (%)</label>
                    <input type="number" className="w-full border border-slate-200 rounded-xl px-4 py-2" defaultValue={settingsData.battery_min_soc} />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Max SOC (%)</label>
                    <input type="number" className="w-full border border-slate-200 rounded-xl px-4 py-2" defaultValue={settingsData.battery_max_soc} />
                  </div>
                </div>
                <button className="mt-4 bg-emerald-500 text-white rounded-xl py-3 font-bold hover:bg-emerald-600 transition-colors" onClick={() => showToast("Settings saved successfully to backend.")}>Save Configuration</button>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
